from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import cm
from datetime import date

def generate_invoice_pdf(invoice, tenant_name="Enterprise ERP Core"):
    """Generates a professional PDF for an Invoice"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    
    elements = []
    
    # Header
    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=24, textColor=colors.HexColor("#195bac"), spaceAfter=12)
    elements.append(Paragraph(f"INVOICE #{invoice.id}", title_style))
    elements.append(Paragraph(f"Date: {invoice.invoice_date or date.today()}", styles['Normal']))
    elements.append(Paragraph(f"Due Date: {invoice.due_date or 'N/A'}", styles['Normal']))
    elements.append(Paragraph(f"Status: {invoice.status}", styles['Normal']))
    elements.append(Spacer(1, 1*cm))
    
    # Addresses
    data = [
        [Paragraph(f"<b>ISSUER</b><br/>{tenant_name}<br/>Financial Node Alpha", styles['Normal']), 
         Paragraph(f"<b>BILL TO</b><br/>{invoice.customer_name}<br/>Verified Commercial Partner", styles['Normal'])]
    ]
    t = Table(data, colWidths=[8.5*cm, 8.5*cm])
    elements.append(t)
    elements.append(Spacer(1, 1*cm))
    
    # Items Table
    data = [["Description", "Qty", "Unit Price", "Subtotal"]]
    for line in invoice.lines:
        data.append([
            line.description,
            str(line.quantity),
            f"${float(line.unit_price):,.2f}",
            f"${float(line.amount):,.2f}"
        ])
    
    # Totals
    data.append(["", "", "<b>GRAND TOTAL</b>", f"<b>${float(invoice.total_amount):,.2f}</b>"])
    
    table = Table(data, colWidths=[8.5*cm, 2*cm, 3*cm, 3.5*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#64748b")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -2), 0.1, colors.lightgrey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LINEBELOW', (0, -1), (-1, -1), 1, colors.HexColor("#195bac")),
    ]))
    
    elements.append(table)
    
    # Footer
    elements.append(Spacer(1, 3*cm))
    elements.append(Paragraph("<b>FINANCIAL DISCLOSURE</b>", styles['SmallItalic'] if 'SmallItalic' in styles else styles['Italic']))
    elements.append(Paragraph("This document is a certified financial record generated by the Enterprise ERP Core. All amounts are in base currency unless specified. Please settle outstanding balances by the due date to avoid service disruption.", styles['Normal']))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()

def generate_bill_pdf(bill, tenant_name="Enterprise ERP Core"):
    """Generates a professional PDF for a Purchase Bill"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    
    elements = []
    
    # Header
    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=24, textColor=colors.HexColor("#e11d48"), spaceAfter=12)
    elements.append(Paragraph(f"PURCHASE BILL #{bill.id}", title_style))
    elements.append(Paragraph(f"Date: {bill.bill_date or date.today()}", styles['Normal']))
    elements.append(Paragraph(f"Due Date: {bill.due_date or 'N/A'}", styles['Normal']))
    elements.append(Paragraph(f"Status: {bill.status}", styles['Normal']))
    elements.append(Spacer(1, 1*cm))
    
    # Addresses
    data = [
        [Paragraph(f"<b>VENDOR</b><br/>{bill.vendor_name}<br/>Strategic Supplier Node", styles['Normal']), 
         Paragraph(f"<b>RECEIVER</b><br/>{tenant_name}<br/>Operational Hub", styles['Normal'])]
    ]
    t = Table(data, colWidths=[8.5*cm, 8.5*cm])
    elements.append(t)
    elements.append(Spacer(1, 1*cm))
    
    # Items Table
    data = [["Description", "Qty", "Unit Price", "Subtotal"]]
    for line in bill.lines:
        data.append([
            line.description,
            str(line.quantity),
            f"${float(line.unit_price):,.2f}",
            f"${float(line.amount):,.2f}"
        ])
    
    # Totals
    data.append(["", "", "<b>TOTAL PAYABLE</b>", f"<b>${float(bill.total_amount):,.2f}</b>"])
    
    table = Table(data, colWidths=[8.5*cm, 2*cm, 3*cm, 3.5*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#fff1f2")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#9f1239")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -2), 0.1, colors.lightgrey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LINEBELOW', (0, -1), (-1, -1), 1, colors.HexColor("#e11d48")),
    ]))
    
    elements.append(table)
    
    # Footer
    elements.append(Spacer(1, 3*cm))
    elements.append(Paragraph("<b>ACCOUNTS PAYABLE NOTE</b>", styles['Italic']))
    elements.append(Paragraph("This liability has been recorded in the central ledger. Unauthorized modifications or removal will trigger a compliance audit.", styles['Normal']))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
