"""sync_crm_schema

Revision ID: fa1805e01f76
Revises: 
Create Date: 2026-03-08 09:13:50.710584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa1805e01f76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_id'), 'bom', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_maintenance', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=True)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_number', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity_planned', sa.Float(), nullable=False),
    sa.Column('quantity_produced', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_wo_number'), 'work_orders', ['wo_number'], unique=True)
    op.drop_index(op.f('idx_ledger_batch'), table_name='inventory_stock_ledger')
    op.drop_index(op.f('idx_ledger_item'), table_name='inventory_stock_ledger')
    op.drop_index(op.f('idx_ledger_serial'), table_name='inventory_stock_ledger')
    op.drop_index(op.f('idx_ledger_tenant'), table_name='inventory_stock_ledger')
    op.drop_index(op.f('idx_ledger_wh'), table_name='inventory_stock_ledger')
    op.drop_table('inventory_stock_ledger')
    op.add_column('crm_activities', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crm_activities', 'crm_customers', ['customer_id'], ['id'])
    op.add_column('crm_deals', sa.Column('probability', sa.Integer(), nullable=True))
    op.add_column('crm_deals', sa.Column('expected_close_date', sa.DateTime(), nullable=True))
    op.add_column('crm_leads', sa.Column('company', sa.String(), nullable=True))
    op.add_column('crm_leads', sa.Column('source', sa.String(), nullable=True))
    op.drop_constraint(op.f('finance_accounts_code_key'), 'finance_accounts', type_='unique')
    op.create_unique_constraint('uq_account_code_tenant', 'finance_accounts', ['code', 'tenant_id'])
    op.add_column('finance_bill_lines', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_finance_bill_lines_tenant_id'), 'finance_bill_lines', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'finance_bill_lines', 'tenants', ['tenant_id'], ['id'])
    op.add_column('hrm_employees', sa.Column('role', sa.String(), nullable=True))
    op.add_column('hrm_employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hrm_employees', 'hrm_departments', ['department_id'], ['id'])
    op.create_index(op.f('ix_inventory_bins_tenant_id'), 'inventory_bins', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'inventory_bins', 'tenants', ['tenant_id'], ['id'])
    op.add_column('scm_shipments', sa.Column('estimated_arrival', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scm_shipments', 'estimated_arrival')
    op.drop_constraint(None, 'inventory_bins', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_bins_tenant_id'), table_name='inventory_bins')
    op.drop_constraint(None, 'hrm_employees', type_='foreignkey')
    op.drop_column('hrm_employees', 'department_id')
    op.drop_column('hrm_employees', 'role')
    op.drop_constraint(None, 'finance_bill_lines', type_='foreignkey')
    op.drop_index(op.f('ix_finance_bill_lines_tenant_id'), table_name='finance_bill_lines')
    op.drop_column('finance_bill_lines', 'tenant_id')
    op.drop_constraint('uq_account_code_tenant', 'finance_accounts', type_='unique')
    op.create_unique_constraint(op.f('finance_accounts_code_key'), 'finance_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('crm_leads', 'source')
    op.drop_column('crm_leads', 'company')
    op.drop_column('crm_deals', 'expected_close_date')
    op.drop_column('crm_deals', 'probability')
    op.drop_constraint(None, 'crm_activities', type_='foreignkey')
    op.drop_column('crm_activities', 'customer_id')
    op.create_table('inventory_stock_ledger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batch_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('serial_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('ref_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['inventory_bins.id'], name=op.f('inventory_stock_ledger_bin_id_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('inventory_stock_ledger_item_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_stock_ledger_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], name=op.f('inventory_stock_ledger_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_stock_ledger_pkey'))
    )
    op.create_index(op.f('idx_ledger_wh'), 'inventory_stock_ledger', ['warehouse_id'], unique=False)
    op.create_index(op.f('idx_ledger_tenant'), 'inventory_stock_ledger', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_ledger_serial'), 'inventory_stock_ledger', ['serial_no'], unique=False)
    op.create_index(op.f('idx_ledger_item'), 'inventory_stock_ledger', ['item_id'], unique=False)
    op.create_index(op.f('idx_ledger_batch'), 'inventory_stock_ledger', ['batch_no'], unique=False)
    op.drop_index(op.f('ix_work_orders_wo_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_bom_id'), table_name='bom')
    op.drop_table('bom')
    # ### end Alembic commands ###
